name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          source .venv/bin/activate # Activate venv again for this step
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
      - name: Lint with flake8
        run: |
          source .venv/bin/activate # Activate venv again for this step
          pip install flake8
          flake8 app/ scripts/
      - name: Convert NeMo to ONNX model
        run: |
          source .venv/bin/activate # Activate venv for script
          python scripts/convert_to_onnx.py
        # Add a timeout here if the conversion can take a long time
        timeout-minutes: 5 # Adjust as needed
      - name: Start FastAPI application
        run: |
          source .venv/bin/activate
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
        timeout-minutes: 1
      - name: Run tests
        run: |
          source .venv/bin/activate # Activate venv again for this step
          python scripts/test_transcription.py --num-files 1 || true
      - name: Stop FastAPI application (optional, good practice)
        if: always()
        run: |
          pkill -f uvicorn || true
      - name: Build Docker image
        run: |
          docker build -t hindi-asr-app .
